projects:
  default:
    schema:
      - ${MAGENTO_BACKEND_URL}/graphql
      - "**/client-schema.graphql"
    documents:
      - '../{peregrine,venia-ui,venia-concept}/{lib,src}/**/!(*.spec).js'
      - '!**/*.ce.js'
    extensions:
      codegen:
        generates:
          ./merged-schema.v4.json:
            plugins:
              - introspection
